CREATE DATABASE flipkarts;
use flipkarts;

select * from mobiles;

SELECT 
BRAND,
sum(case when MRP BETWEEN 0 AND 9999 THEN 1 ELSE 0 END) AS 'Price Below 10k',
sum(case when MRP BETWEEN 10000 AND 19999 THEN 1 ELSE 0 END) AS 'Price Between 10-20k',
sum(case when MRP BETWEEN 20000 AND 39999 THEN 1 ELSE 0 END) AS 'Price Below 20-40k',
sum(case when MRP >= 40000 THEN 1 ELSE 0 END) AS 'Price Below 40k'
from 
mobiles
GROUP BY 
BRAND 
ORDER BY BRAND;

SELECT BRAND, MAX(MRP - MSP) AS MAXDISCOUNT
FROM MOBILES
GROUP BY BRAND
ORDER BY MAXDISCOUNT DESC
LIMIT 1;

SELECT BRAND, AVG(RATINGS) AS AVG_RATING
FROM MOBILES
GROUP BY BRAND
ORDER BY AVG_RATING DESC
LIMIT 5;

SELECT BRAND, SUM(NO_OF_REVIEWS) AS TOTAL_REVIEWS
FROM MOBILES
GROUP BY BRAND
ORDER BY TOTAL_REVIEWS DESC
LIMIT 5;

SELECT * FROM MOBILES
WHERE RATINGS > 4.5;

SELECT * FROM MOBILES
WHERE DISCOUNT > 40;

SELECT BRAND, AVG(RATINGS) AS AVG_RATING, SUM(NO_OF_REVIEWS) AS TOTAL_REVIEWS 
FROM MOBILES
GROUP BY BRAND
ORDER BY AVG_RATING DESC;

SELECT  * FROM MOBILES
ORDER BY DISCOUNT DESC 
LIMIT 5;

SELECT DISTINCT BRAND FROM MOBILES;
select * from mobiles;